language: node_js
rvm: 2.7.0
before_install:
- npm install
- gem install bundler -v 2.3.26
- gem install nypl_ruby_util
install:
- pip install awscli
cache: bundler
script:
- npm run test
before_deploy:
- rm -rf vendor
deploy:
- provider: lambda
  edge: true
  function_name: Redirect-qa
  description: Redirects old webpac requests to Research Catalog
  region: us-east-1
  role: arn:aws:iam::946183545209:role/lambda-full-access
  runtime: nodejs14.x
  module_name: index
  handler_name: handler
  skip_cleanup: true
  access_key_id: "$AWS_ACCESS_KEY_ID_QA"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY_QA"
  environment:
   - BASE_SCC_URL=qa-www.nypl.org/research/research-catalog
   - CAS_SERVER_DOMAIN=nypl-sierra-test.nypl.org
   - ENCORE_URL=qa-redir-browse.nypl.org
   - LEGACY_CATALOG_URL=nypl-sierra-test.nypl.org
   - REDIRECT_SERVICE_DOMAIN=qa-redir-browse.nypl.org
   - VEGA_AUTH_DOMAIN=nypl.na2.iiivega.com
   - VEGA_URL=nypl.na2.iiivega.com
   - FOO=bar
  on:
    branch: qa
- provider: lambda
  function_name: Redirect-production
  description: Redirects old webpac requests to Research Catalog
  region: us-east-1
  role: arn:aws:iam::946183545209:role/lambda-full-access
  runtime: nodejs14.x
  module_name: index
  handler_name: handler
  skip_cleanup: true
  access_key_id: "$AWS_ACCESS_KEY_ID_PRODUCTION"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY_PRODUCTION"
  environment:
   - BASE_SCC_URL=www.nypl.org/research/research-catalog
   - CAS_SERVER_DOMAIN=ilsstaff.nypl.org
   - ENCORE_URL=browse.nypl.org
   - LEGACY_CATALOG_URL=legacycatalog.nypl.org
   - REDIRECT_SERVICE_DOMAIN=redir-browse.nypl.org
   - VEGA_AUTH_DOMAIN=auth.na2.iiivega.com
   - VEGA_URL=nypl.na2.iiivega.com
  on:
    branch: production
after_deploy:
- rake set_config
env:
  global:
    secure: aHSbyJymjjLvkIBbayDFt7B37iqmzQVGsvtCKMOFIE0rNXZJup9iC7gFOSHUOq1rtl08is0+bu2bikyNiETZ+fos/m+ICo5C42N0NRQsY2qPlGyXOXmAibos7Jmw3MB5rJ2puQJ0L8mB0JU5txnsN55vipO4jDKed+de/QDFFop8wMDiZ/DZR07tjCwNflp2LqwXWR9Swzo/XbRYwG/NYZLRnaHc8QF9CNBwPN60z2ro4IsCDBozUo+/uiQkcSU+GDkZHCTjlpjQv2GXQQLOYx0MWYB0qwwhe9wvvR4tjgEmmnuRePecniiGQq5yu/nP2ZFyqMqrBo2JapRM++AOv0xkHa+CExwQ6dJDck+G75LU0jQnYhde/3OOdZeO/ZJ43wbDhT64DI6gRmsvbapColX9fkrglSNAjx/L4O33SDNn5Zui0DgRtuQXs0Ofr/ZgGnHjdrrlxl05Gkdmmyz09pfLJp2Mi3beSlF69vAStEnNhOhzwYbmauTu/KKcAFoCfjcyp8LTY9dLPhYfCDT6W2fViSe5xJ6mkD0ycMOL3DxCKHriEqDZ4CBrHamEHRIOFhZGpkUyI2QlgtOHqg+q0b11jC8+mls8n1Uh+aiXetiOf8iV2aDOuw9NanhRczJ4d/Su0mAu2V9VH1ceTkiPDq9OnPv06F5mJPANj34vSxs=
