AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'redirect service'

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 300
    Environment:
      Variables:
        BASE_SCC_URL: qa-discovery.nypl.org/research/collections/shared-collection-catalog
        CLASSIC_CATALOG_URL: qa-catalog.nypl.org
        LEGACY_CATALOG_URL: catalog.nypl.org

Resources:
  RedirectService:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Handler: index.handler
      Runtime: nodejs12.x
