AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'redirect service'

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 300
    Environment:
      Variables:
        BASE_SCC_URL: qa-www.nypl.org/research/research-catalog
        LEGACY_CATALOG_URL: nypl-sierra-test.nypl.org
        ENCORE_URL: qa-redir-browse.nypl.org
        VEGA_URL: nypl.na2.iiivega.com
        ENCORE_URL: qa-redir-browse.nypl.org
        CAS_SERVER_DOMAIN: nypl-sierra-test.nypl.org
        REDIRECT_SERVICE_DOMAIN: qa-redir-browse.nypl.org
        ENVIRONMENT: qa
        # SKIP_VEGA_LOGOUT: true
Resources:
  RedirectService:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Handler: index.handler
      Runtime: nodejs12.x
      Events:
        RedirectServiceRoot:
          Type: Api
          Properties:
            Path: /
            Method: any
        RedirectServiceCatchAll:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any
