AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'redirect service'

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 300
    Environment:
      Variables:
        BASE_SCC_URL: qa-discovery.nypl.org/research/collections/shared-collection-catalog/
        CLASSIC_CATALOG_URL: https://catalog.nypl.org
        CLIENT_ID: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAGkwZwYJKoZIhvcNAQcGoFowWAIBADBTBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDMH033iRCWL2fqZIHgIBEIAmPHu+9wBZjnZSqLa4HMi2U33pHdmVFo2pfx5nrKKYCicoyAUHhJU=
        CLIENT_SECRET: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAIcwgYQGCSqGSIb3DQEHBqB3MHUCAQAwcAYJKoZIhvcNAQcBMB4GCWCGSAFlAwQBLjARBAwbvdh+2ByuGqN69hkCARCAQwceJ6Hc6gHSYvPsde6e3zrAXiC676UO1ICVVYRmEGYh6R4wwuEFi5RuQoZXBVIDiwoMM/iE0KkQjoKE7TQghDEp1yM=
        OAUTH_URL: https://isso.nypl.org/oauth/token
        PLATFORM_BASE_URL: https://qa-platform.nypl.org/api/v0.1

Resources:
  RedirectService:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Handler: index.handler
      Runtime: nodejs12.x
